CompileFlags:
    Add:
      [
        -Wno-documentation,
        -Wno-missing-prototypes,
      ]
Diagnostics:
  ClangTidy:
    Add:
    [
        performance-*,
        bugprone-*,
        clang-analyzer-*,
        readability-identifier-*
    ]
    Remove:
    [
        bugprone-easily-swappable-parameters,
        bugprone-narrowing-conversions,
        readability-identifier-length
    ]
    # CheckOptions:
    #   readability-identifier-naming.VariableCase: camelCase
